RESULTS_DIR: results
RUN_NAME: collab_amb
AUTO_INCREMENT: true

grid_size: 30
noise_std: 0.0
num_uavs: 2
num_ugvs: 2
steps: 200

ugv_depth: 7
reward_type: 6
ugv_amb_lambda: 5.0
discount_factor: 0.95

gp_sensing_noise_sigma0: 1.0e-6
gp_max_basis: 150
gp_threshold_delta: 0.05

rbf_sigma: 2.0

cfg:
  use_cbf: true
  waypoint_mode: miyashita
  #waypoint_mode: suenaga_dp
  #waypoint_mode: ugv_future_point
  #waypoint_mode: common_weighted

  #nominal_mode: to_waypoint
  #nominal_mode : to_ugv_future
  #nominal_mode: to_ugv_future_if_in_voronoi_else_waypoint
  nominal_mode: to_ugv_reachable_best_amb
  #nominal_mode: to_ugv_high_variance_if_in_voroni_else_waypoint


  nominal_hold_steps: 10


  use_voronoi: true

  use_common_map: true
  common_map_mode: direction
  #common_map_mode:point
  ugv_weight_eta: 0.3

  d0: 5.0
  ugv_future_path_sigma: 5.0
  step_of_ugv_path_used: 7

  ring_d_star: 8.0
  ring_sigma: 4.0

  suenaga_rho: 0.95
  suenaga_depth: 5

  k_pp: 1.0
  k_ugv: 1.0
  v_limit: 5.0
  num_poly: 8
  control_period: 0.1
  gp_update_period: 0.5

  cbf_j_alpha: 0.01
  cbf_j_gamma: 6.0

  signal_mode: gp_logistic_prob
  #signal_mode: gp_mean

  #uav_waypoint_signal: gp_var
  uav_waypoint_signal: prob_ambiguity

  map_publish_period: 0.5

  dir_num_steps: 8
  dir_ell_u: 6.0
  dir_ell_perp: 3.0
  dir_eta_forward: 2.0
  dir_forward_shift: 0.0
  dir_mode: sum
  dir_normalize: true

  wp_use_topk_centroid: false
  wp_topk: 60
  wp_min_dist: 2.0
  wp_power: 1.0

  ugv_move_period: 10

  use_local_sogp_delta: false
  local_sogp_radius: 7.0
  local_sogp_delta_scale: 0.8

calibrator:
  threshold: 0.7
  init_w: 1.0
  lr: 0.03
  l2: 0.0001
  min_samples: 20

ground_truth:
  num_blobs: 100
  amp_range: [1.0, 3.0]
  sigma_range: [0.8, 1.8]
  background: 0.02
  noise_std: 0.02
  max_value: 1.0
  num_runs: 20

#init_position_mode: ugv_left_bottom_uav_right_top_cluster
init_position_mode: random

init:
  margin: 3
  spacing: 5

gp_prior_mean_mode: zero
#gp_prior_mean_mode: threshold

gp_prior_mean_value: 0.5